---
abstract: 'Configurable URIs for Catalyst'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Action::REST: 0
  Catalyst::Controller: 0
  Catalyst::Test: 0
  File::Spec: 0
  FindBin: 0
  HTTP::Request: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  URI::SmartURI: 0
  lib: 0
  parent: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-SmartURI
no_index:
  directory:
    - t
requires:
  Catalyst::Exception: 0
  Catalyst::Request: 0
  Class::C3::Componentised: 0
  Class::Load: 0
  Moose: 0
  Scalar::Util: 0
  mro: 0
  namespace::clean: 0
  perl: 5.008001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-SmartURI
  homepage: http://metacpan.org/release/Catalyst-Plugin-SmartURI
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rkitover/catalyst-plugin-smarturi.git
version: 0.039
x_authority: cpan:RKITOVER
